services:
  - type: web
    name: breast-cancer-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r analysis/requirements.txt
    startCommand: uvicorn api_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0